# Generated by Django 4.2.10 on 2024-02-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayusage',
            name='usage_date',
            field=models.DateField(auto_now=True),
        ),
    ]
